'use client'
import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import injectContext from './store/appContext'

const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}

export default injectContext(RootLayout);
